Adding tests to CI
risi-kondor/GElib pull request #5
Opened 2023-06-27 13:26 UTC by agoscinski

Hello,

### Summary

this PR adds the GitHub actions that executes existing tests and added doctests that are taken from the documentation. The action is executed for each commit to main branch and pull request. I renamed the tests to the pattern `test_<NAME>` so pytest automatically discovers them. 

### Tests are failing
This test was failing `tests/manual_tests/test_square_activation_2.py` but here I just needed to change the import.
These tests are failing and I could not fix them so I commented them out:
- python/tests/manual_tests/test_FFT_accuracies.py # I put the error message in the file, seems like an easy fix
- python/tests/test_SO3vecArr.py # here the values are extremely off from the reference, not sure what is wrong here, but seems to be harder to fix
This I cannot fix by myself, so I would need someone to help me.

### Example in python doctstring that are tested in CI
I added into the python docstring of the function `SO3vec.randn` as in the example documentation. The docstring examples are also tested by the CI.

As soon as the tests are fixed, I check if the examples from the python docstring already appear in the documentation, then I can move most examples (maybe even all) from the documentation to python docstrings.

2023-06-28 11:31 UTC, risi-kondor reviewed
Thanks! Some of the features in these tests like the FFT are not in the stable part of the code yet, so we don't need to include them in the CI.

2023-06-28 12:18 UTC, risi-kondor requested changes
Which tests are included in the CI exactly? Can we please exclude the `manual_tests` directory from automatic testing?

2023-06-29 11:55 UTC, agoscinski commented
All tests in the test directory which have a function called test* or filenames that are called test_*
You can see what the CI is doing here in the `.github/workflows/tests.yml` file
https://github.com/agoscinski/GElib/blob/test-ci/.github/workflows/tests.yml

This runs the test
```bash
pytest python/tests
```

This command executes the code in the python docstring and checks if the output matches the output of 
```bash
pytest --doctest-modules --pyargs gelib
```
which you find here for example https://github.com/agoscinski/GElib/blob/d772801b6c0659062f9f1443cb8537b92e1a33be/python/src/gelib/SO3vec.py#L55-L75

I moved all tests outside of the manual_tests folder to a ci_tests folder which is now scanned by pytest

2023-06-29 15:24 UTC, risi-kondor approved these changes

2023-06-29 15:27 UTC, merged